#!/usr/bin/env bash
# This file is a leftover/mistyped location ('.github/worfkflows'). GitHub Actions reads .github/workflows/.
# The real workflow has been added at: .github/workflows/dokka.yml
# You can remove this file to avoid confusion.

echo "Deprecated: .github/worfkflows/dokka.yml. Use .github/workflows/dokka.yml"
exit 0
